version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    volumes:
      - ./code:/var/www/html  # Montage du répertoire local vers le conteneur
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: eleve
      MYSQL_PASSWORD: eleve
    volumes:
      - dbdata:/var/lib/mysql  # Volume persistant pour la base de données
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql  # Assurez-vous que cela correspond au nom du service MySQL
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: eleve
      PMA_PASSWORD: eleve
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  dbdata:  # Volume persistant pour les données MySQL
    driver: local

networks:
  app_network:
    driver: bridge